name: Build
on: [push]
jobs: 
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  unit-tests:
    runs-on: ubuntu-latest
    needs: python-formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install pytest
      - name: Install Flask
        run: pip install Flask
      - name: Run tests
        run: pytest app_test.py


  deploy-to-impaas:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ImPaaS-Deploy
        uses: /impaas/impaas-deploy@v4
        with:
          app-name: alexmiriamapp
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM




